import { defineType, defineField } from 'sanity';

export const project = defineType({
  name: 'project',
  title: 'Project',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Title', type: 'string', validation: r => r.required() }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title' }, validation: r => r.required() }),
    defineField({ name: 'subtitle_nl', title: 'Subtitle (NL)', type: 'string' }),
    defineField({ name: 'subtitle_en', title: 'Subtitle (EN)', type: 'string' }),
    defineField({ name: 'description_nl', title: 'Description (NL)', type: 'text', rows: 3 }),
    defineField({ name: 'description_en', title: 'Description (EN)', type: 'text', rows: 3 }),
    defineField({ name: 'image', title: 'Cover Image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'screenshots', title: 'Screenshots', type: 'array', of: [{ type: 'image', options: { hotspot: true }, fields: [{ name: 'caption', title: 'Caption', type: 'string' }] }] }),
    defineField({ name: 'featured', title: 'Featured?', type: 'boolean', initialValue: false }),
    defineField({ name: 'comingSoon', title: 'Coming Soon?', type: 'boolean', initialValue: false }),
    defineField({ name: 'color', title: 'Brand Color (hex)', type: 'string', initialValue: '#023047' }),
    defineField({ name: 'year', title: 'Year', type: 'string' }),
    defineField({ name: 'role', title: 'Role', type: 'string' }),
    defineField({ name: 'techStack', title: 'Tech Stack', type: 'array', of: [{ type: 'string' }] }),
    defineField({ name: 'url', title: 'Live URL', type: 'url' }),
    defineField({ name: 'problem_nl', title: 'Challenge (NL)', type: 'text' }),
    defineField({ name: 'problem_en', title: 'Challenge (EN)', type: 'text' }),
    defineField({ name: 'solution_nl', title: 'Solution (NL)', type: 'text' }),
    defineField({ name: 'solution_en', title: 'Solution (EN)', type: 'text' }),
    defineField({ name: 'results_nl', title: 'Results (NL)', type: 'array', of: [{ type: 'string' }] }),
    defineField({ name: 'results_en', title: 'Results (EN)', type: 'array', of: [{ type: 'string' }] }),
    defineField({ name: 'order', title: 'Order', type: 'number' }),
  ],
  orderings: [{ title: 'Order', name: 'order', by: [{ field: 'order', direction: 'asc' }] }],
  preview: { select: { title: 'title', subtitle: 'subtitle_nl', media: 'image' } },
});
